import type { Metadata } from 'next'
import './globals.css'
import Script from 'next/script'

export const metadata: Metadata = {
  title: 'Josh Jones - GRC Engineering & Security Automation Specialist',
  description: 'josh@joshdoes.it:~$ whoami\n\nGRC Engineering & Security Automation Specialist. Operationalizing GRC programs through code, integrations, and workflow automation across enterprise environments.',
  openGraph: {
    title: 'Josh Jones - View CV & Portfolio',
    description: 'https://joshdoes.it',
    url: 'https://joshdoes.it',
    images: [
      {
        url: 'https://joshdoes.it/og-image.png',
        width: 1200,
        height: 630,
        alt: 'Josh Jones - GRC Engineering & Security Automation Specialist',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Josh Jones - View CV & Portfolio',
    description: 'https://joshdoes.it',
    images: ['https://joshdoes.it/og-image.png'],
  },
  appleWebApp: {
    title: 'Josh Jones',
  },
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/favicon.ico', type: 'image/x-icon' },
    ],
    apple: [
      { url: '/favicon.ico', sizes: '180x180', type: 'image/x-icon' },
    ],
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
        <link rel="apple-touch-icon" href="/favicon.ico" />
        <meta name="apple-mobile-web-app-title" content="Josh Jones" />
        {/* OG tags are generated by Next.js metadata API - don't duplicate here */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                'use strict';
                // Suppress harmless errors from third-party scripts (Disqus/Google Sign-In)
                // These errors don't affect functionality but clutter the console
                
                // CRITICAL: Wrap MutationObserver IMMEDIATELY before any scripts load
                // This must run before any third-party scripts that use MutationObserver
                // We need to intercept at the prototype level to catch all instances
                (function() {
                  if (typeof MutationObserver === 'undefined') return;
                  
                  const OriginalMutationObserver = window.MutationObserver || MutationObserver;
                  
                  // Store original observe method
                  const OriginalObserve = OriginalMutationObserver.prototype.observe;
                  
                  // Override observe on the prototype to catch all instances
                  OriginalMutationObserver.prototype.observe = function(target, options) {
                    // Validate target - return silently if invalid
                    if (!target || typeof target !== 'object') {
                      return;
                    }
                    // Check if target is a Node instance
                    if (!(target instanceof Node)) {
                      return; // Silently fail - this prevents the error
                    }
                    
                    try {
                      return OriginalObserve.call(this, target, options);
                    } catch (e) {
                      // Suppress all MutationObserver-related errors
                      return;
                    }
                  };
                  
                  // Also replace the constructor to ensure new instances use our wrapper
                  window.MutationObserver = function(callback) {
                    const observer = new OriginalMutationObserver(callback);
                    // The prototype override already handles observe, but ensure it's bound
                    return observer;
                  };
                  
                  // Preserve prototype and static properties
                  Object.setPrototypeOf(window.MutationObserver, OriginalMutationObserver);
                  window.MutationObserver.prototype = OriginalMutationObserver.prototype;
                  
                  // Also set on global scope if different
                  if (typeof MutationObserver !== 'undefined' && MutationObserver !== window.MutationObserver) {
                    MutationObserver = window.MutationObserver;
                  }
                })();
                
                // Override console.error to filter harmless third-party errors
                if (typeof console !== 'undefined') {
                  const originalError = console.error;
                  console.error = function(...args) {
                    const message = String(args.join(' '));
                    // Suppress MutationObserver errors (multiple patterns)
                    if (
                      message.includes('MutationObserver') ||
                      (message.includes('observe') && message.includes('instance of Node')) ||
                      message.includes('credentials-library.js') ||
                      // Suppress Disqus cross-origin frame errors (expected browser security warning)
                      (message.includes('Blocked a frame') && message.includes('disqus.com')) ||
                      (message.includes('from accessing a frame') && message.includes('origin'))
                    ) {
                      return; // Suppress this error
                    }
                    originalError.apply(console, args);
                  };
                  
                  // Suppress Google deprecation warnings
                  const originalWarn = console.warn;
                  console.warn = function(...args) {
                    const message = String(args.join(' '));
                    if (
                      (message.includes('deprecated') && message.includes('Google') && message.includes('authentication')) ||
                      (message.includes('Migration Guide') && message.includes('identity/gsi'))
                    ) {
                      return; // Suppress this warning
                    }
                    originalWarn.apply(console, args);
                  };
                }
                
                // Global error handler to catch uncaught exceptions
                // Must use capture phase and be registered early
                if (typeof window !== 'undefined') {
                  // Use capture phase to intercept errors before they propagate
                  window.addEventListener('error', function(event) {
                    const errorMessage = event.message || '';
                    const errorFilename = event.filename || '';
                    
                    if (
                      errorMessage.includes('MutationObserver') ||
                      errorMessage.includes('must be an instance of Node') ||
                      errorMessage.includes('observe') ||
                      errorFilename.includes('credentials-library.js') ||
                      errorFilename.includes('embed.js') ||
                      errorFilename.includes('embedv2.js') ||
                      // Suppress Disqus cross-origin frame errors (expected browser security warning)
                      (errorMessage.includes('Blocked a frame') && errorMessage.includes('disqus.com')) ||
                      (errorMessage.includes('from accessing a frame') && errorMessage.includes('origin'))
                    ) {
                      event.preventDefault();
                      event.stopPropagation();
                      event.stopImmediatePropagation();
                      return true; // Prevent default error handling
                    }
                    return false;
                  }, true); // Use capture phase
                  
                  // Handle unhandled promise rejections
                  window.addEventListener('unhandledrejection', function(event) {
                    const reason = event.reason;
                    if (reason) {
                      const reasonMessage = (typeof reason === 'object' && reason.message) ? reason.message : String(reason);
                      if (
                        reasonMessage.includes('MutationObserver') ||
                        reasonMessage.includes('must be an instance of Node') ||
                        reasonMessage.includes('observe')
                      ) {
                        event.preventDefault();
                        return true;
                      }
                    }
                    return false;
                  }, true);
                  
                }
              })();
            `,
          }}
        />
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js"
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className="bg-terminal-bg text-terminal-green font-mono">
        {children}
      </body>
    </html>
  )
}

