import type { Metadata } from 'next'
import './globals.css'
import Script from 'next/script'

export const metadata: Metadata = {
  title: 'Josh Jones - GRC Engineering & Security Automation Specialist',
  description: 'josh@joshdoes.it:~$ whoami\n\nGRC Engineering & Security Automation Specialist. Operationalizing GRC programs through code, integrations, and workflow automation across enterprise environments.',
  openGraph: {
    title: 'Josh Jones - View CV & Portfolio',
    description: 'https://joshdoes.it',
    url: 'https://joshdoes.it',
    images: [
      {
        url: 'https://joshdoes.it/og-image.png',
        width: 1200,
        height: 630,
        alt: 'Josh Jones - GRC Engineering & Security Automation Specialist',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Josh Jones - View CV & Portfolio',
    description: 'https://joshdoes.it',
    images: ['https://joshdoes.it/og-image.png'],
  },
  appleWebApp: {
    title: 'Josh Jones',
  },
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/favicon.ico', type: 'image/x-icon' },
    ],
    apple: [
      { url: '/favicon.ico', sizes: '180x180', type: 'image/x-icon' },
    ],
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
        <link rel="apple-touch-icon" href="/favicon.ico" />
        <meta name="apple-mobile-web-app-title" content="Josh Jones" />
        {/* OG tags are generated by Next.js metadata API - don't duplicate here */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                'use strict';
                // Suppress harmless errors from third-party scripts (Disqus/Google Sign-In)
                // These errors don't affect functionality but clutter the console
                
                // CRITICAL: Wrap MutationObserver IMMEDIATELY before any scripts load
                if (typeof MutationObserver !== 'undefined') {
                  const OriginalMutationObserver = MutationObserver;
                  MutationObserver = function(callback) {
                    const observer = new OriginalMutationObserver(callback);
                    const originalObserve = observer.observe.bind(observer);
                    observer.observe = function(target, options) {
                      // Validate target before calling observe
                      if (!target || typeof target !== 'object' || !(target instanceof Node)) {
                        return; // Silently fail if target is invalid
                      }
                      try {
                        return originalObserve.call(this, target, options);
                      } catch (e) {
                        // Suppress all MutationObserver errors from third-party scripts
                        if (!e || !e.message || e.message.includes('must be an instance of Node') || e.message.includes('MutationObserver')) {
                          return;
                        }
                        throw e;
                      }
                    };
                    return observer;
                  };
                  // Preserve prototype chain
                  Object.setPrototypeOf(MutationObserver, OriginalMutationObserver);
                  MutationObserver.prototype = OriginalMutationObserver.prototype;
                }
                
                // Override console.error to filter MutationObserver errors
                if (typeof console !== 'undefined') {
                  const originalError = console.error;
                  console.error = function(...args) {
                    const message = String(args.join(' '));
                    // Suppress MutationObserver errors (multiple patterns)
                    if (
                      message.includes('MutationObserver') ||
                      (message.includes('observe') && message.includes('instance of Node')) ||
                      message.includes('credentials-library.js')
                    ) {
                      return; // Suppress this error
                    }
                    originalError.apply(console, args);
                  };
                  
                  // Suppress Google deprecation warnings
                  const originalWarn = console.warn;
                  console.warn = function(...args) {
                    const message = String(args.join(' '));
                    if (
                      (message.includes('deprecated') && message.includes('Google') && message.includes('authentication')) ||
                      (message.includes('Migration Guide') && message.includes('identity/gsi'))
                    ) {
                      return; // Suppress this warning
                    }
                    originalWarn.apply(console, args);
                  };
                }
                
                // Global error handler to catch uncaught exceptions
                if (typeof window !== 'undefined') {
                  window.addEventListener('error', function(event) {
                    if (
                      event.message &&
                      (
                        event.message.includes('MutationObserver') ||
                        event.message.includes('must be an instance of Node') ||
                        (event.filename && event.filename.includes('credentials-library.js'))
                      )
                    ) {
                      event.preventDefault();
                      event.stopPropagation();
                      event.stopImmediatePropagation();
                      return true;
                    }
                    return false;
                  }, true);
                  
                  // Handle unhandled promise rejections
                  window.addEventListener('unhandledrejection', function(event) {
                    if (
                      event.reason &&
                      typeof event.reason === 'object' &&
                      event.reason.message &&
                      event.reason.message.includes('MutationObserver')
                    ) {
                      event.preventDefault();
                      return true;
                    }
                    return false;
                  }, true);
                }
              })();
            `,
          }}
        />
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js"
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className="bg-terminal-bg text-terminal-green font-mono">
        {children}
      </body>
    </html>
  )
}

